### ISSUE TITLE
Can we download a file?

### ISSUE THREAD

**Issue by knowndead** [krizalys/onedrive-php-sdk#10]
So just a question, cause in the example it doesn't seem possible, but can you actually download a file from onedrive with this tool? for what we want to use this project for we pretty much need that.
If not, could you maybe guide me in the right direction for how to do that?
Since im not really used to big projects with custom objects(onedrive object) etc xd i tend to make wordpress plugins mostly.

**Comment by christophe-ddproperty** [comment]
Yes, you can, using `fetchContent()` on a valid `File` object: https://github.com/krizalys/onedrive-php-sdk/blob/master/src/Krizalys/Onedrive/File.php#L58

Please see http://demo.krizalys.com/onedrive-php-sdk/example/ for an example, or the `example` directory for the source code.

**Comment by knowndead** [comment]
Thanks for the reply :)
