### ISSUE TITLE
Create new release (on packagist)

### ISSUE THREAD

**Issue by uuf6429** [krizalys/onedrive-php-sdk#25]
Currently, v1.0.0 is very old and virtually unusable (too many bugs). One cannot simply use this package from composer (unless they resort to using dev-master, which isn't good practice).

Since so far there have been tonnes of actual bug fixes (and not so much breaking changes AFAIK), it would be a good idea to create a release some time soon.

**Comment by krizalys** [comment]
Yes, agree.

The plan is to release a version 1.1.0 with all these fixes. In this version, i'd also like to revise the current API regarding the current way of dealing with temporary files / and file overwrites, I'm aiming to release it this month.

**Comment by DavidAnderson684** [comment]
Though it's a good thing to clear up some of the bugs in a 1.1, I think the major issue is that it's still using the legacy Live API, instead of the current OneDrive API.... the largest challenge for new developers will be that they won't want to use it in a new project when it's using an older API.

**Comment by uuf6429** [comment]
From my perspective, I would have released a1.x with bug fixes and then later on a 2.x with me API.... Doesn't make sense for devs having to wait for critical fixes IMHO.

**Comment by krizalys** [comment]
1.1.0 is out.

Next steps for the 1.x version:

* Improve coverage & test suite
* Improve API documentation
* Add logging capabilities (not before 1.3)
* Use Guzzle (not before 1.4)

I'll probably start working on the 2.x version in parallel, whose major change will be the use the OneDrive API. It will probably not be released in 2016 though :)
