### ISSUE TITLE
create file warning

### ISSUE THREAD

**Issue by rajasharma27** [krizalys/onedrive-php-sdk#26]
when I am using create file show curl error

$parentId    = null;
$name        = 'sample.txt';
$content     = 'this is sample text';
$parent      = $onedrive->fetchObject($parentId);
$file        = $parent->createFile($name, $content);
var_dump($file->getName().' : '.$file->getId());
-----------------------------------------------------------------------------

Warning: curl_setopt_array(): cannot represent a stream of type MEMORY as a STDIO FILE  in  in onedrive-php-sdk-master\src\Krizalys\Onedrive\Client.php on line 515

file create but contents not saved

**Comment by rajasharma27** [comment]
thanks

**Comment by krizalys** [comment]
Thanks for the feedback. I cannot reproduce this issue however.

Can you please share more code? And more detail about your OS, PHP version, etc... ?

**Comment by rajasharma27** [comment]
I am using windows10 and PHP Version 7.0.5

**Comment by rajasharma27** [comment]
<?php
session_start();
require_once 'onedrive-config.php';
require_once 'onedrive-php-sdk-master/vendor/autoload.php';

use Krizalys\Onedrive\Client;
// Clears the session and restarts the whole authentication process
//$_SESSION = array();

if(!isset($_GET['code'])){  // && !isset($_SESSION['onedrive.client.state'])){
// Instantiates a OneDrive client bound to your OneDrive application
$onedrive = new \Krizalys\Onedrive\Client(array(
    'client_id' => ONEDRIVE_CLIENT_ID
));

// Gets a log in URL with sufficient privileges from the OneDrive API
$url = $onedrive->getLogInUrl(array(
    'wl.signin',
    'wl.basic',
	'wl.offline_access',
    'wl.contacts_skydrive',
    'wl.skydrive_update',
	
), ONEDRIVE_CALLBACK_URI);

// Persist the OneDrive client' state for next API requests
$_SESSION['onedrive.client.state'] = $onedrive->getState();
echo "<a href='$url'>Next step</a>";
}else{

// Attempt to load the OneDrive client' state persisted from the previous
// request

if (!array_key_exists('onedrive.client.state', $_SESSION)) {
    throw new Exception('onedrive.client.state undefined in $_SESSION');
}

if(empty($_SESSION['onedrive.client.state']->token)){

	$onedrive = new \Krizalys\Onedrive\Client(array(
    	'client_id' => ONEDRIVE_CLIENT_ID,

    	// Restore the previous state while instantiating this client to proceed in
    	// obtaining an access token
    	'state'     => $_SESSION['onedrive.client.state']
));

// Obtain the token using the code received by the OneDrive API
$onedrive->obtainAccessToken(ONEDRIVE_CLIENT_SECRET, $_GET['code']);

// Persist the OneDrive client' state for next API requests
$_SESSION['onedrive.client.state'] = $onedrive->getState();
}

// Past this point, you can start using file/folder functions from the SDK

$onedrive = new \Krizalys\Onedrive\Client(array(
	'state' => $_SESSION['onedrive.client.state']
));

$itemId = 'me/skydrive';

try{
	$parentId    = null;
	$name        = 'sample.txt';
	$content     = 'this is sample text';
	$parent   = $onedrive->fetchObject($parentId);
    $file     = $parent->createFile($name, $content ,$options = array());
    $status   = sprintf('<p class=bg-success>The file <em>%s</em> has been created using the <code>Object::createFile</code> method.</p>', htmlspecialchars($name));
} catch (\Exception $e) {
    $file   = null;
    $status = sprintf('<p class=bg-danger>The file <em>%s</em> has <strong>not</strong> been created using the <code>Object::createFile</code> method. Reason: <cite>%s</cite></p>', htmlspecialchars($name), $e->getMessage());
}

}

?>

**Comment by krizalys** [comment]
Hi, thanks for the sample code.

I believe there is still an issue on some systems where curl would refuse to work with memory streams.

Usually, it can be avoided by using temporary streams instead, example: https://github.com/zachborboa/php-curl-class/commit/4cb1436983bd7c73096bdcd0461b9a3bf4d12998, I will experiment a similar solution and let you test it.

So can you try to use temporary stream instead:

```php
<?php

$client = new Client([
    'stream_back_end' => StreamBackEnd::TEMP,
    // More options here...
]);

// More code here...
```

Let me know if it solves your issue.

**Comment by rajasharma27** [comment]
not working showing error
Fatal error: Uncaught Error: Class 'StreamBackEnd' not found

**Comment by krizalys** [comment]
Sorry, my example implied that you `use` both the `Client` and the `StreamBackEnd` classes:

```php
<?php

// Include autoload.php here

use Krizalys\Onedrive\Client;
use Krizalys\Onedrive\StreamBackEnd;

$client = new Client([
    'stream_back_end' => StreamBackEnd::TEMP,
    // More options here...
]);

// More code here...

```

**Comment by rajasharma27** [comment]
Sir,
now working perfectly using with

use Krizalys\Onedrive\Client;
use Krizalys\Onedrive\StreamBackEnd;

$client = new Client([
    'stream_back_end' => StreamBackEnd::TEMP,
    // More options here...
]);

thanks

**Comment by rajasharma27** [comment]
sir,
one more issue
how to enable every time app approve prompt using with
scopes 'wl.offline_access'

**Comment by rajasharma27** [comment]
sir,
when use $onedrive->updateObject($itemId, $properties,$contents); for update contents of file

nothing to save when text file without error
and when use in image showing error data is not json type

**Comment by rajasharma27** [comment]
sir,
I am facing problem when update contents in existing file in onedirve
how to update contents in file
please help

**Comment by rajasharma27** [comment]
ok now update existing file contents
thanks

**Comment by krizalys** [comment]
I added an integration test for binary files (eg. images). It's passing and I did not get the error you reported.

Please kindly send me full code samples if you report further issues.
