### ISSUE TITLE
Demo website linked to in the README.MD produces 500 errors

### ISSUE THREAD

**Issue by michael-langford** [krizalys/onedrive-php-sdk#27]
When visiting the demo website linked to in the README you are greeted with the following error (http://demo.krizalys.com/onedrive-php-sdk/example/):

Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /homepages/33/d259274170/htdocs/chroot/usr/share/domain/krizalys.com/demo/onedrive-php-sdk/example/index.php on line 5

**Comment by krizalys** [comment]
Thanks for reporting this.

I cannot reproduce this issue (it currently works without having changed anything). It could be due an occasional hosting provider issue and/or wrong PHP version selected to serve the request (line 5 reads `use Krizalys\Onedrive\Client;` and would be considered a parse error on older PHP versions).

Could you please kindly try again and let me know the exact steps/URL to follow to observe this error if it persists?

Thanks.

**Comment by michael-langford** [comment]
It is working now
