### ISSUE TITLE
Difference between Organizational/ business Account and Personal Account

### ISSUE THREAD

**Issue by gargsuchi** [krizalys/onedrive-php-sdk#28]
Hi Krizalys
Thanks for this awesome SDK.

I was trying to use this SDK but am facing 2 weird issues:

1. I have a personal account, using which I am able to check the folder shared with me. But when I use this API, and list out the FetchRoot - I am not able to see the shared folder. Please note that the URL of the shared folder is not https://onedrive.live.com . So my question is, how to use this SDK for OneDrive for Business.
2. I uploaded a file to my onedrive manually. Now, when I am trying to fetch that file using FetchFile (and giving correct ID), the SDK provides some details of the file, but the content part of the result is empty. 

Can you please help us out.

**Comment by krizalys** [comment]
Thanks for the report @gargsuchi.

1. Did you try calling `Client::fetchShared` instead of `Client::fetchRoot`? https://github.com/krizalys/onedrive-php-sdk/issues/28
2. This could be due to your PHP/cURL version, could you kindly tell me more about your environment?

Thank you.

**Comment by surbz** [comment]
Hi Krizalys
Thanks for replying us.

1.Yes we tried Client::fetchShared but its returning us blank array, though folder is shared from a business account to my personal account. But neither we are able to see this folder in my personal account nor its coming in the Client::fetchShared  array.

2.Following are our environment details  -
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
PHP 5.6.10

@gargsuchi

**Comment by krizalys** [comment]
V2 is out, it's using MS Graph API (rather than Windows Live API) maybe it solves your problem.
