### ISSUE TITLE
[Question] What OneDrive URI to use with the Office protocol?

### ISSUE THREAD

**Issue by chris-fa** [krizalys/onedrive-php-sdk#29]
I'm posting this here cause after 2 days I'm unable to find any info, so I'm getting desperate, I apologize beforehand.

When fetching a `.docx` file, `$onedrive` returns an object containing properties, like this:

```
stdClass Object
(
    [id] => file.A1B2C3D4.A1B2C3D4!100
    ...
    [name] => Test document.docx
    ...
    [upload_location] => https://apis.live.net/v5.0/file.A1B2C3D4.A1B2C3D4!100/content/
    ...
    [source] => https://4k3emw-dm2306.files.1drv.com/som-random-string/Test%20document.docx?psid=1
    [link] => https://onedrive.live.com/redir.aspx?cid=A1B2C3D4&page=view&resid=A1B2C3D4!112&parId=D7C6A1C2!101
    ...
)
```

Which one of those should I use to build the protocol `ms-word:ofe%7Cu%7Chttps:// <URL>`

Thanks in advance

**Comment by krizalys** [comment]
I'm not sure that OneDrive supports this natively. At first glance, I could not find anything in their documentation.

I found this: http://stackoverflow.com/questions/22987005/is-there-an-application-url-protocol-for-ms-word
Perhaps you could try to build such a URL from any of these 3 OneDrive URLs and see if it magically works?

I'm closing this for now, but if you find a way to do this, feel free to reopen or send a pull request.
