### ISSUE TITLE
How code callback.php

### ISSUE THREAD

**Issue by AndreaYoung9x** [krizalys/onedrive-php-sdk#30]
I do not see the file callback.php
please send it to me, I thank you!

**Comment by krizalys** [comment]
You are supposed to create this file yourself. Its purpose is:

# Set the state of the client from your configuration and previous instantiations
# Obtain an access token using `Client::obtainAccessToken()`

Here is an example: https://github.com/krizalys/onedrive-php-sdk/blob/master/example/auth.php#L23-L32

I will add a note to the README.
