### ISSUE TITLE
Multipart upload support

### ISSUE THREAD

**Issue by dustinbolton** [krizalys/onedrive-php-sdk#33]
Does this library support multipart uploads? I need to be able to break up uploading across multiple page loads for large files.  OneDrive supports this as seen here: https://dev.onedrive.com/items/upload_post.htm

I need this because my app runs on users' shared hosting accounts which tend to have unmodifiable maximum execution time limits and slow speeds so I need to be able to break it up.  I do this with Amazon S3, Dropbox, Google Drive, Rackspace, etc within my app but I'd like to use this library to add OneDrive support but this is critical for my use case.

**Comment by krizalys** [comment]
No, there is no support of this feature at this point. It is on my roadmap for the V2.

**Comment by krizalys** [comment]
Added support for this feature in 2.1.0. See `DriveItemProxy::startUpload()`: https://github.com/krizalys/onedrive-php-sdk/blob/master/src/Proxy/DriveItemProxy.php#L322

**Comment by tudders** [comment]
Hi Mate. Great library! Can you provide an example of calling DriveItemProxy::startUpload().

Cheers

**Comment by krizalys** [comment]
> Hi Mate. Great library! Can you provide an example of calling DriveItemProxy::startUpload().
> 
> Cheers

Sure. Here is an example from the functional test suite:

https://github.com/krizalys/onedrive-php-sdk/blob/master/test/functional/KrizalysOnedriveTest.php#L1318-L1327
