### ISSUE TITLE
upload image from url

### ISSUE THREAD

**Issue by foxpcteam** [krizalys/onedrive-php-sdk#35]
Hi,
I trying to upload image using your example create-file.php.
in the content field i give full image url and give the image name.jpg
when i go to my onedrive, i see the file but the file is corrupted.

so how can i upload image that will work?

Thanks

**Comment by krizalys** [comment]
Instead of its URL, try passing either the *content* of the file (for example obtained by `file_get_contents()`) or a *resource* representing the opened file (for example obtained by `fopen()`).

If this does not solve it, please provide some sample code.

**Comment by krizalys** [comment]
Assuming that it worked as expected.
