### ISSUE TITLE
PHP 7.2 (current RC2) does not allow `Object` as class name

### ISSUE THREAD

**Issue by VolCh** [krizalys/onedrive-php-sdk#36]
https://github.com/php/php-src/blob/php-7.2.0RC2/UPGRADING#L44

It used in https://github.com/krizalys/onedrive-php-sdk/blob/master/src/Krizalys/Onedrive/Object.php

**Comment by krizalys** [comment]
Thanks, I'll have a look into this.

**Comment by DavidAnderson684** [comment]
Hi @krizalys , if you've got anything that can be tested, then I'd be glad to assist. since PHP 7.2 is due out in a couple of weeks ( http://php.net/archive/2017.php#id2017-11-09-1 ).

**Comment by krizalys** [comment]
Fixed in 1.2.0 (without API change) and in master (with API change).
