### ISSUE TITLE
 Live sdk api has deprecated  since a year and will not continue after November 1, 2018

### ISSUE THREAD

**Issue by pmbaldha** [krizalys/onedrive-php-sdk#38]
As per migration guide on https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk , The live sdk api has deprecated  since a year and will not continue after November 1, 2018. This paragraph is as below:

> Live SDK and Live Connect APIs have been marked as deprecated for over a year. As announced on the Office Developer blog, these APIs are now end of life and will no longer
> be available after November 1, 2018.

You can see it on relevant screenshot: https://imgur.com/a/Oyj1G

So after November 1, 2018, this library will not work due to expiry of live sdk. 

Also, There are onedrive for business is not with live sdk api. 

There is migration guide on https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk

From https://docs.microsoft.com/en-us/onedrive/developer/rest-api/:

> OneDrive REST API is a portion of the Microsoft Graph API which allows your app to connect to content stored in OneDrive and SharePoint. The REST API is shared between OneDrive, OneDrive for Business, SharePoint document libraries, and Office Groups, to allow your app the flexibility to read and store content in any of these locations with the same code.

May i know have you any plan to migrate Live sdk to Microsoft Graph rest api? 

Thank you very very much in advance. I hall wait for your reply.

**Comment by krizalys** [comment]
Hi @pmbaldha, thanks for reporting this.

Fortunately, yes, I already have plans & committed some effort to migrate to the Microsoft Graph REST API. I just hope that I will find the time to do so before November 18.

Please feel free to reopen this if you have further questions.
