### ISSUE TITLE
Save files to OneDrive using PHP but same FTP without show login page for access_token

### ISSUE THREAD

**Issue by kamelj** [krizalys/onedrive-php-sdk#39]
I'm wondering if I can use OneDrive for saving integration files between two web apps, so I have to create file and save it to OneDrive on specific folder but this process should be in background using username and password for OneDrive account, so the end user should not see the Microsoft login page or asking them about this app to allow access to his info, (by the way I don't need any information from end user) All what I want is to upload the integration files to specific OneDrive account on specific action exactly same FTP on PHP.

Please any suggestions or solutions?

**Comment by krizalys** [comment]
Hi @kamelj, when using OAuth (as used by OneDrive API), you need to log in at least once on the vendor's (Microsoft) site. This also allows you to grant permissions requested by the app.

With that being said, if you use refresh tokens, you can:

1. log in once
2. get your first token
3. get a refresh token (see `Client::renewAccessToken()`) whenever it expires

You can theoretically repeat step 3 indefinitely without having to log in again.

Another strategy could involve browser automation, for example using Selenium. This approach is more complex, but you should be able to simulate the log in step which you are currently performing manually.
