### ISSUE TITLE
Upload Support - "Create file"

### ISSUE THREAD

**Issue by pebbledesigns** [krizalys/onedrive-php-sdk#41]
Great SDK by the way. Really helped me to get started. 

I wondered if there was any more information about uploading files from local machine. I see we have "Creating a OneDrive file" with a content field but I wondered if i had a zip, or image what would the steps be (if it can handle this method)?

**Comment by krizalys** [comment]
Hi, thanks for the support.

Both `Folder::createFile()` and `Client::createFile()` support `string`s and `resource`s as the file `$content` parameter.  The value is normalized to a generic PHP stream internally before being sent to the API.

In your example, you can try passing a `resource`, for example an open file, eg:

```php
$myFile = fopen('localfile.zip', 'r');
$myClient->createFile('remotefile.zip', $myParentId, $myFile);
fclose($myFile);
```

If this does not solve your problem, feel free to reopen this ticket.

**Comment by pebbledesigns** [comment]
Hi @krizalys, thank you for your response. I will have a look and update you shortly.

In regards to files larger than 4mb (current limit) is there anything we can do?
