### ISSUE TITLE
Share Link

### ISSUE THREAD

**Issue by akshayshuklaa** [krizalys/onedrive-php-sdk#43]
Not been able to create a share link for an item. Please help me with ths

**Comment by landall** [comment]
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online

Will you share sth from OneDrive Personal or from OneDrive Business?

**Comment by krizalys** [comment]
@akshayshuklaa Added support for sharing links in 2.4.0, just released.

 See:

* https://github.com/krizalys/onedrive-php-sdk/blob/master/src/Proxy/DriveItemProxy.php#L937
* https://github.com/krizalys/onedrive-php-sdk/wiki/Krizalys-Onedrive-Proxy-DriveItemProxy#createlink

**Comment by karinnahmay** [comment]
@krizalys , i tried using the implementation for getting shareable link but i got an empty result. 
 here is my code:

$stream = fopen($path_file, 'rb');
  $upload = $dataItem->startUpload(basename($path_file), $stream);
  $driveItem = $upload->complete();
  $permission = $dataItem->createLink("view");

Thanks for the help in advance!

**Comment by krizalys** [comment]
@karinnahmay Thanks for reporting that to me. By "empty result", do you mean that `$permission == null;`, or something else?

**Comment by karinnahmay** [comment]
@krizalys yes, it gives an empty result; i tried to log it but its empty. Any reasons for this? Thanks!
