### ISSUE TITLE
Need to be updated to Microsoft Graph API before Nov 1, 2018

### ISSUE THREAD

**Issue by landall** [krizalys/onedrive-php-sdk#44]
Live SDK and Live Connect APIs have been marked as deprecated for over a year. As announced on the Office Developer blog, these APIs are now end of life and will no longer be available after November 1, 2018.

Profile and contacts data will no longer be available from the Live Connect APIs as of Decmeber 1, 2017. Calendar data has not been available from Live Connect since June 2017.

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk?view=odsp-graph-online

**Comment by krizalys** [comment]
Definitely trying to push a new version supporting the new API.

**Comment by krizalys** [comment]
Done in V2.

**Comment by landall** [comment]
Great to update it!
