### ISSUE TITLE
Reason: curl_exec() failed: SSL read: errno -5961

### ISSUE THREAD

**Issue by landall** [krizalys/onedrive-php-sdk#46]
Notice: Undefined property: stdClass::$access_token in /var/www/html/onedrive-php-sdk/src/Krizalys/Onedrive/Client.php on line 544

I cannot run the example with a libcurl error about ssl. What should i do?

**Comment by krizalys** [comment]
This seems to be because Onedrive did not send back an access token to your application.

Could you tell me more about your application config (app type, redirect URL, etc...) on your Microsoft account?

**Comment by krizalys** [comment]
In V2, we do not use curl directly by ourselves and delegate this responsibility to Guzzle & Microsoft Graph SDK. You may want to try this version and see if it fixes your problem.

**Comment by landall** [comment]
I will try it this week! Thanks for your job!
