### ISSUE TITLE
Lack of Feature: RemoteItem

### ISSUE THREAD

**Issue by landall** [krizalys/onedrive-php-sdk#48]
Coming From: 
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online

I think DriveItem should add some method to check if it is a remote item and get the real DriveItem from its placeholder.

**Comment by krizalys** [comment]
@landall This is already possible, via [DriveItemProxy::$remoteItem](https://github.com/krizalys/onedrive-php-sdk/blob/2.5.0/src/Proxy/DriveItemProxy.php#L56) - this property is set if the drive item is a remote item and provides information on the actual drive item referred to.

As of version 2.5.0, the [RemoteItemProxy API became more complete](https://github.com/krizalys/onedrive-php-sdk/blob/2.5.0/src/Proxy/RemoteItemProxy.php#L23-L54) and this information is available through its `$parentReference`.
