### ISSUE TITLE
Cannot use token from state

### ISSUE THREAD

**Issue by landall** [krizalys/onedrive-php-sdk#55]
I find there is no way to use a access token stored in state options.
There is only one setAccessToken called in obtain token from code.
$this->graph->setAccessToken($this->_state->token->data->access_token);

**Comment by tudders** [comment]
If you're refreshing the token, the refreshToken method doesn't set the access token. I added a line in the method to set the access token so the object can use the token when calling endpoints.

**Comment by landall** [comment]
> If you're refreshing the token, the refreshToken method doesn't set the access token. I added a line in the method to set the access token so the object can use the token when calling endpoints.

I add a method named restoreAccessToken to do this.

**Comment by krizalys** [comment]
@landall @tudders You seem to have fixed this issue in your own copy of the library.

Please kindly consider opening a PR/test case so I can understand the issue better and your fix can benefit other users.

**Comment by krizalys** [comment]
@landall @tudders Please could you kindly share your fix with me if you want this to be solved for everyone?

**Comment by tudders** [comment]
Hey there - this is my change.
![image](https://user-images.githubusercontent.com/20762224/61419846-f9787b80-a93e-11e9-87c5-701865d45120.png)

**Comment by krizalys** [comment]
@landall @tudders This is fixed in `2.1.2`.
