### ISSUE TITLE
How to convert a DriveItemProxy to an array or object?

### ISSUE THREAD

**Issue by landall** [krizalys/onedrive-php-sdk#56]
I want to show the directory info about a drive or a folder. how to convert a DriveItemProxy to an array or object so that i can print it out with foreach.

**Comment by krizalys** [comment]
@landall If you need to list the contents (files & folders in a given folder), try https://github.com/krizalys/onedrive-php-sdk/blob/master/src/Proxy/DriveItemProxy.php#L211:

```php
foreach ($myFolderDriveItem->getChildren() as $child) {
  var_dump($child); // you may need to call further APIs on $child, which is itself a DriveItemProxy
}
```

If you need to see the meta data, simply call the relevant getters on DriveItemProxy, for example:

```php
var_dump($myFolderDriveItem->cTag); // prints the CTag
```
