### ISSUE TITLE
Onedrive novice - help needed

### ISSUE THREAD

**Issue by adrian2020** [krizalys/onedrive-php-sdk#58]
Hi,
I have a requirement to allow users logged into to our company-use-only website to upload/download files from known folders. Currently am using Dropbox but would now like to use Onedrive, I not have to login separately to Onedrive (as user has already authenticated and identified themselves logging into our main website).
Is this code that can do that ?

Can you confirm it is not going to be out of date / deprecated soon ?
Compared to Dropbox the development learning curve seems a bit steeper requiring
  - A OneDrive web application configured with http://localhost:7777/ as its redirect URL
  - A WebDriver server, for example the Selenium's Java standalone server
  - A Chrome browser & ChromeDriver, and they must be usable by the WebDriver server

To date I just use a local xampp setup to develop on and then upload to a shared web server.

Any advice to get over this hurdle welcome .

Thanks

**Comment by krizalys** [comment]
Hi @adrian2020.
First of all, kindly apologize for the the late response.
Now, to answer your questions:

> Is this code that can do that ?

Yes, web applications registered in Onedrive seem to allow any domain, whether it is publicly accessible or not, but with the limitation that, except for localhost, **it must be reached through HTTPS**.

In your case, you may try to register a web application with a redirect URL such as: https://my-company-private-domain.com/ where this domain need not resolve from people outside of your company network.


> Can you confirm it is not going to be out of date / deprecated soon ?

This library was recently updated to support the new Onedrive API, so I do not plan to stop supporting it soon.
However, please note that I maintain it on my free time and can commit only limited time to it.
For this reason, I am open to contributions :)


> Compared to Dropbox the development learning curve seems a bit steeper requiring

Please note that this flow is governed by Onedrive's design, not by this library. Onedrive currently uses the OAuth protocol, and this is the way that a web application/library interacts with this protocol.

If this flow does not meet your requirements/is different from what Dropbox is doing, you can try to enquire directly Onedrive's operator (Microsoft) for alternatives. If there are, and if they are publicly documented, I will be happy to consider supporting them in this library.
