### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by feesler** [krizalys/onedrive-php-sdk#59]
In the readme there is the link to the project page: [http://www.krizalys.com/software/onedrive-php-sdk](http://www.krizalys.com/software/onedrive-php-sdk) But unfortunately it leads to the blank page.
So it impossible to see available/recommended API of the library and use cases.

**Comment by krizalys** [comment]
@feesler I mirrored the README contents to this page - this is the only documentation available at this point.
