### ISSUE TITLE
Separate out HTTP consumer, or use Guzzle

### ISSUE THREAD

**Issue by DavidAnderson684** [krizalys/onedrive-php-sdk#6]
This library contains its own private functions for calling curl, which is a bit inflexible.

It'd be best to either:
1) Separate out the HTTP consumer into a separate class, and pass that... e.g.:

```
$consumer = new \OneDrive\Curl_Consumer(); // Object which contains all the current HTTP classes used in this SDK
$onedrive = new \OneDrive\Client($options, $consumer); // Consumer is passed to client, which calls its methods
```

This allows someone to build their own replacement consumer class, whilst still having curl available as a convenient default for people who don't need to do anything fancy.

or

2) Use Guzzle, which is flexible enough to allow pretty much anything to be done with it, and isn't tied to curl (though defaults to curl). Guzzle is used in this way by the Amazon Web Services and Rackspace OpenCloud PHP SDKs, amongst others.

This isn't so exciting or needful to me that I'm likely to do it (though I'd probably use it if it were provided). I just mention it as something that would be an improvement.

**Comment by krizalys** [comment]
Thanks for the suggestion.

I have also been considering using Guzzle, but did not found the time to actually implement it, yet. Let's add this to the roadmap of the first stable release.

**Comment by DavidAnderson684** [comment]
That makes sense. A first stable also ought to update to the current API... I wrote a patch to handle chunked/resumable uploading using that API, but didn't send it in, as it was a different API to the one you're currently using. And it required tweaks in the various apiGET|POST|PUT methods too... I think I've sent in all the patches I made apart from that one...

**Comment by krizalys** [comment]
Done in V2.
