### ISSUE TITLE
Automatically Refresh Token?

### ISSUE THREAD

**Issue by solepixel** [krizalys/onedrive-php-sdk#64]
Thanks for sharing this library! My only previous experience with an OAuth library is with [thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client) and whenever the token had expired, a new one was generated with the Refresh Token automatically.

I have noticed that once you authorize the application, the token is only good for the first expiration period. After it expires, it makes no attempt to use the RefreshToken to generate a new OAuth token.

Is there a built in method for handling an OAuth token refresh in your SDK? If not, do you have a recommended way of handling getting a new Token? I'd be happy to look into contributing something that handles this if one does not already exist.

Expected Behavior:

1. Authorize Application
1. Make an API call with OAuth Token
1. If Token has expired, automatically retrieve a new Token with RefreshToken before continuing with API call.
1. Complete API call successfully with new Token.

Actual Behavior:

1. Authorize Application
1. Make an API call with OAuth Token
1. If Token has expired, API call fails since it does not renew the Token.
1. API call does not complete successfully using expired Token.

Thanks, please let me know if I can help any further!

**Comment by krizalys** [comment]
@solepixel True, this library currently does not renew the access token by itself.

As a workaround, your app can currently:
1. Check whether the current access token is expiring soon, using Client::getAccessTokenStatus(): see https://github.com/krizalys/onedrive-php-sdk/blob/2.5.0/src/Client.php#L314
2. If expiring, renew the token by itself, using Client::renewAccessToken(): see https://github.com/krizalys/onedrive-php-sdk/blob/2.5.0/src/Client.php#L404 (the offline_access scope must have been given when you initiated the OAuth authorization)

I welcome your help on this, please be informed that in version 3, I am considering to delegate the whole OAuth flow management to the client library you are suggesting. Please allow me some time to think about this design, I'll get back to you.

**Comment by krizalys** [comment]
@solepixel Glanced into the [thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client) project and according to their README, it seems to me that refreshing a token is not done automatically and instead needs to be done from the application.

Am I understanding correctly? In any case, please could you kindly provide code samples subject to 
OAuth token autorefresh?

**Comment by solepixel** [comment]
Sorry about the delay. You're correct, I reviewed my code using this library and it looks (roughly) something like this:
```php
public function get_auth() {
    if ( is_object( $this->auth ) ) {
        if ( $this->auth->hasExpired() ) {
            $this->refresh_token();
        }
        return $this->auth;
    }
    return false;
}
public function refresh_token() {
    $provider = $this->get_oauth_provider( 'refresh_token' );
    try {
        $new_access_token = $provider->getAccessToken(
           'refresh_token',
            array(
                'refresh_token' => $this->auth->getRefreshToken(),
            )
        );
    } catch ( Exception $e ) {
        if ( 'invalid_grant' === $e->getMessage() ) {
            return false;
        }
    }
    // Store $new_access_token
    return $new_access_token;
}
```
The library does make it pretty simple to keep it updated, and I'm refreshing it anytime it needs refreshing. Hope that helps!

**Comment by krizalys** [comment]
Thanks @solepixel, I'm now 90% convinced that I should go with the thephpleague/oauth2-client in version 3 and added this to the roadmap. Everything still needs to be done, but let's see if we can get there. Closing this for now.
