### ISSUE TITLE
authorization without visualization in the browser

### ISSUE THREAD

**Issue by Artem2710** [krizalys/onedrive-php-sdk#68]
Hello! Is there any code example how to make authorization without visualization in the browser? Or how can I upload and download files onedrive if I already know the token? Very grateful.

**Comment by krizalys** [comment]
> Is there any code example how to make authorization without visualization in the browser?

(copied from https://github.com/krizalys/onedrive-php-sdk/issues/67)

@Artem2710 OAuth is designed specifically to allow users to delegate to tiers access to their accounts without giving their credentials to those tiers. If you are unfamiliar with OAuth, there is a good summary here: https://medium.com/@somindagamage/oauth-2-0-for-dummies-8807cff5c3b2

Please understand that **the whole idea is not to annoy your users, but rather, to build trust between them and you application** - ie. when asked to give their credentials, your users may trust a reputable company (Microsoft) more than your application. This is why OAuth specifically requires authentication to be handled exclusively by the provider (Microsoft).

With that being said, there are ways to work around it, all with some drawbacks:

1. you can following the example design I have shown above - the best solution because it is a use case supported by OAuth, but users still need to log in to Microsoft at least once
2. you can automate a headless web browser to perform the authorization without visual feedback, as show in the functional tests - not recommended on production due to the unreliability of browser automation
3. instead of a full-blown web browser, you can theoretically perform the authorization using a lower-level HTTP client, such as curl, by sending carefully-crafted requests to the authorization server and reacting to responses appropriately - not sure if it's even possible, but it is probably as unreliable as the above

**Please be warned that using 2 and 3 in a way that involves your users disclosing their credentials to your application defeats the purposes of OAuth. It may even be a violation of Microsoft terms of service.**


> Or how can I upload and download files onedrive if I already know the token?

Absolutely, yes! The main limitation is that access tokens have an expiration date - it is your responsibility to renew them before they expire. If you do this right, your users don't need to log in again. Here the example I gave to another user showing you how to do that - please update to meet your requirements:

```php
// Gets your user ID in $userId somehow - note that this ID has nothing to do
// with the OneDrive user ID and would be maintained in your own user table

$rows = executeSql("SELECT state FROM onedrive_state WHERE user_id = $user_id");

// User never logged in to OneDrive via your app - let them do so and persist
// their state in your DB
// This is the only time the user would need to log in to OneDeive - afterwards
// the token will always be coming from your DB, and refreshed when it expires
if (empty($rows)) {
    $client = Onedrive::client('YOUR_ONEDRIVE_CLIENT_ID');

    $url = $client->getLogInUrl([
        'offline_access', // This is required for renewing tokens
        // ...
    ], 'index.php');

    $state = $client->getState();
    $stateJson = json_encode($state);
    executeSql("INSERT INTO onedrive_state(user_id, state) VALUES ($userId, $stateJson)");
    header('HTTP/1.1 302 Found', true, 302);
    header("Location: $url");
    exit 0;
}

// User previously logged in to Onedrive via your app - you either need to
// finalize the authentication by obtaining a token and persisting in your DB,
// or renew the it if it has expired and update it in your DB
$state = json_decode($rows[0]->state);
$client = Onedrive::client('YOUR_ONEDRIVE_CLIENT_ID', ['state' => $rows[0]->state]);

// If you get called with a code in the URL, the user was just redirected from
// OneDrive after you redirected them here to let them log in - you are now
// finalizing the authentication by getting an access token and updating the
// state in your DB
if ($_GET['code']) {
    $client->obtainAccessToken('YOUR_ONEDRIVE_CLIENT_SECRET', $_GET['code']);
    $state = $client->getState();
    $stateJson = json_encode($state);
    executeSql("UPDATE onedrive_state SET state = '$stateJson' WHERE user_id = $userId)");

// Otherwise, you need to check if the token you have in your records in still
// valid and renew it if not - the state also needs to be updated in your DB so
// the token shows as valid for a little while
} else {
    $tokenObtainTime = $state->token->obtained;
    $tokenExpirationTime = timeAdd(time(), $state->token->data->expires_in);

    if (timeCompare($tokenObtainTime, $tokenExpirationTime, '<=')) {
        $client->renewAccessToken('YOUR_ONEDRIVE_SECRET');
        $state = $client->getState();
        $stateJson = json_encode($state);
        executeSql("UPDATE onedrive_state SET state = '$stateJson' WHERE user_id = $userId)");
    }
}

// You can now use the client
$file = $client->getRoot()->upload('hello.txt', 'Hello World!');
echo $file->download();
// => Hello World!
```

**Comment by Artem2710** [comment]
Thank you very much for the answer. Can you tell me how I can download a file knowing its id?

**Comment by osemk** [comment]
> > Is there any code example how to make authorization without visualization in the browser?
> 
> (copied from #67)
> 
> @Artem2710 OAuth is designed specifically to allow users to delegate to tiers access to their accounts without giving their credentials to those tiers. If you are unfamiliar with OAuth, there is a good summary here: https://medium.com/@somindagamage/oauth-2-0-for-dummies-8807cff5c3b2
> 
> Please understand that **the whole idea is not to annoy your users, but rather, to build trust between them and you application** - ie. when asked to give their credentials, your users may trust a reputable company (Microsoft) more than your application. This is why OAuth specifically requires authentication to be handled exclusively by the provider (Microsoft).
> 
> With that being said, there are ways to work around it, all with some drawbacks:
> 
> 1. you can following the example design I have shown above - the best solution because it is a use case supported by OAuth, but users still need to log in to Microsoft at least once
> 2. you can automate a headless web browser to perform the authorization without visual feedback, as show in the functional tests - not recommended on production due to the unreliability of browser automation
> 3. instead of a full-blown web browser, you can theoretically perform the authorization using a lower-level HTTP client, such as curl, by sending carefully-crafted requests to the authorization server and reacting to responses appropriately - not sure if it's even possible, but it is probably as unreliable as the above
> 
> **Please be warned that using 2 and 3 in a way that involves your users disclosing their credentials to your application defeats the purposes of OAuth. It may even be a violation of Microsoft terms of service.**
> 
> > Or how can I upload and download files onedrive if I already know the token?
> 
> Absolutely, yes! The main limitation is that access tokens have an expiration date - it is your responsibility to renew them before they expire. If you do this right, your users don't need to log in again. Here the example I gave to another user showing you how to do that - please update to meet your requirements:
> 
> ```
> // Gets your user ID in $userId somehow - note that this ID has nothing to do
> // with the OneDrive user ID and would be maintained in your own user table
> 
> $rows = executeSql("SELECT state FROM onedrive_state WHERE user_id = $user_id");
> 
> // User never logged in to OneDrive via your app - let them do so and persist
> // their state in your DB
> // This is the only time the user would need to log in to OneDeive - afterwards
> // the token will always be coming from your DB, and refreshed when it expires
> if (empty($rows)) {
>     $client = Onedrive::client('YOUR_ONEDRIVE_CLIENT_ID');
> 
>     $url = $client->getLogInUrl([
>         'offline_access', // This is required for renewing tokens
>         // ...
>     ], 'index.php');
> 
>     $state = $client->getState();
>     $stateJson = json_encode($state);
>     executeSql("INSERT INTO onedrive_state(user_id, state) VALUES ($userId, $stateJson)");
>     header('HTTP/1.1 302 Found', true, 302);
>     header("Location: $url");
>     exit 0;
> }
> 
> // User previously logged in to Onedrive via your app - you either need to
> // finalize the authentication by obtaining a token and persisting in your DB,
> // or renew the it if it has expired and update it in your DB
> $state = json_decode($rows[0]->state);
> $client = Onedrive::client('YOUR_ONEDRIVE_CLIENT_ID', ['state' => $rows[0]->state]);
> 
> // If you get called with a code in the URL, the user was just redirected from
> // OneDrive after you redirected them here to let them log in - you are now
> // finalizing the authentication by getting an access token and updating the
> // state in your DB
> if ($_GET['code']) {
>     $client->obtainAccessToken('YOUR_ONEDRIVE_CLIENT_SECRET', $_GET['code']);
>     $state = $client->getState();
>     $stateJson = json_encode($state);
>     executeSql("UPDATE onedrive_state SET state = '$stateJson' WHERE user_id = $userId)");
> 
> // Otherwise, you need to check if the token you have in your records in still
> // valid and renew it if not - the state also needs to be updated in your DB so
> // the token shows as valid for a little while
> } else {
>     $tokenObtainTime = $state->token->obtained;
>     $tokenExpirationTime = timeAdd(time(), $state->token->data->expires_in);
> 
>     if (timeCompare($tokenObtainTime, $tokenExpirationTime, '<=')) {
>         $client->renewAccessToken('YOUR_ONEDRIVE_SECRET');
>         $state = $client->getState();
>         $stateJson = json_encode($state);
>         executeSql("UPDATE onedrive_state SET state = '$stateJson' WHERE user_id = $userId)");
>     }
> }
> 
> // You can now use the client
> $file = $client->getRoot()->upload('hello.txt', 'Hello World!');
> echo $file->download();
> // => Hello World!
> ```

How you store an object with json? That is not possible. 

>     $state = $client->getState();
>     $stateJson = json_encode($state);

this will always assign $stateJson = "{}". There is a problem with the registration logic and it looks nothing to do to fix it. If you have another method to save state to db please let me know.
