### ISSUE TITLE
Issue on Sharing URL (reference to issue i previously posted; i cant reopen it)

### ISSUE THREAD

**Issue by karinnahmay** [krizalys/onedrive-php-sdk#70]
Hi @krizalys,

This is coming from issue #69 
Unfortunately Shared link is not generated, here is my code:

```
  $stream = fopen($path_file, 'rb');
  $upload = $dataItem->startUpload(basename($path_file), $stream);
  $driveItem = $upload->complete();
  $permission = $dataItem->createLink("view");

```
can you please help or provide instructions on why this happened? Thanks sir!

**Comment by karinnahmay** [comment]
Also one more thing sir, in createLink("view"), this will return the specific file only right? cos based on what i read this will return the whole folder containing the file uploaded. How can i only get the specific file url without viewing the others on that folder?

**Comment by krizalys** [comment]
@karinnahmay There are 2 questions here. I will answer only the 1st one here and request you to open a separate issue for your 2nd question. Thanks.

In your code sample, I noticed that you are not using the same variable name: `$driveItem` on one line and `$dataItem` on the other. Can you fix that and let me know if that solves it? Please reopen if it does not.
