### ISSUE TITLE
createLink no embed type

### ISSUE THREAD

**Issue by karinnahmay** [krizalys/onedrive-php-sdk#71]
@krizalys, I tried using embed feature from https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createlink?view=odsp-graph-online but it gave me an error:

`resulted in a `400 Bad Request` response: { "error": { "code": "invalidRequest", "message": "Link type must be either 'edit' or 'view'.", "inner (truncated...)`

This feature is present based on the graph api, is this implemented on yours?

Thanks!

**Comment by krizalys** [comment]
@karinnahmay Please can you provide some code?

Here is a working example: https://github.com/krizalys/onedrive-php-sdk/blob/2.5.1/test/functional/Proxy/DriveItemProxyTest.php#L811

**Comment by karinnahmay** [comment]
Hi @krizalys,

I used this code: $uploadedFile->createLink("embed", ['scope' => 'anonymous']);

and this caused a problem. 

`resulted in a 400 Bad Request response: { "error": { "code": "invalidRequest", "message": "Link type must be either 'edit' or 'view'.", "inner (truncated...)`

any reasons? i think only view and edit is allowed in your codes?

Thanks!

**Comment by karinnahmay** [comment]
@krizalys and from the view link is it possible to render that in img src on my html?

Thanks!

**Comment by krizalys** [comment]
@karinnahmay `embed` should also work as you can see from the (passing) functional test suite: https://github.com/krizalys/onedrive-php-sdk/blob/2.5.1/test/functional/Proxy/DriveItemProxyTest.php#L913

The documentation states:

> Creates an embeddable link to the DriveItem. **This option is only available for files in OneDrive personal**.

Perhaps you are did not log into a OneDrive personal account? Feel free to reopen if you did.
