### ISSUE TITLE
Download URL

### ISSUE THREAD

**Issue by karinnahmay** [krizalys/onedrive-php-sdk#72]
Hi @krizalys 

is it possible to get the download URL via: 

       ```
 $data = fopen($path_file, 'rb');
        $uploadSession = $dataItem->startUpload(basename($path_file), $data);
        $uploadedFile = $uploadSession->complete();
        $download_link = $dataItem->download();
```
the `$download_link` is giving an error not found:

`{ "error": { "code": "itemNotFound", "message": "You cannot get content for a folder", "innerError": `

**Comment by karinnahmay** [comment]
Hi @krizalys,

tested it via another method and it did return something like this, but how can i download the file itself::

```
GuzzleHttp\Psr7\Stream Object
(
    [stream:GuzzleHttp\Psr7\Stream:private] => Resource id #168
    [size:GuzzleHttp\Psr7\Stream:private] => 
    [seekable:GuzzleHttp\Psr7\Stream:private] => 1
    [readable:GuzzleHttp\Psr7\Stream:private] => 1
    [writable:GuzzleHttp\Psr7\Stream:private] => 1
    [uri:GuzzleHttp\Psr7\Stream:private] => php://temp
    [customMetadata:GuzzleHttp\Psr7\Stream:private] => Array
        (
        )

)
```

**Comment by krizalys** [comment]
@karinnahmay I believe your sample code is incomplete, eg. `$dataItem` is never initialized. If you still need support, please kindly reopen and provide a complete code sample.
