### ISSUE TITLE
Over 4MB size

### ISSUE THREAD

**Issue by emresaracoglu** [krizalys/onedrive-php-sdk#74]
Hey,

I guess if I misunderstood, we don't have a chance to upload files over 4 MB, right?

Thank you @krizalys

**Comment by krizalys** [comment]
@emresaracoglu You can upload big files (over 4 MB) using `DriveItemProxy::startUpload`: https://github.com/krizalys/onedrive-php-sdk/blob/2.5.1/src/Proxy/DriveItemProxy.php#L667

Please see some example usages here: https://github.com/krizalys/onedrive-php-sdk/blob/2.5.1/test/functional/Proxy/DriveItemProxyTest.php#L417
