### ISSUE TITLE
Third party user upload file using pre-defined credential marked on the program

### ISSUE THREAD

**Issue by ahmug** [krizalys/onedrive-php-sdk#75]
Hi Christophe,

I would like to build a page for user to login using our pre-defined login account, not OneDrive account, to upload file to our OneDrive folder. The OneDrive authentication information is hard code on the php page beforehand. Is it feasible? I want to let user upload files without knowing they are uploading to OneDrive.  Please advise. Much thanks.

Joanne

**Comment by krizalys** [comment]
@ahmug No, this is not possible since the OneDrive API is built on OAuth (eg. the user logs into their own account and allows your application to access with restricted permissions).
