### ISSUE TITLE
Potential Fatal Error when Refreshing Token

### ISSUE THREAD

**Issue by solepixel** [krizalys/onedrive-php-sdk#77]
Hi! I'm getting a fatal error at this HTTP Request:
https://github.com/krizalys/onedrive-php-sdk/blob/master/src/Client.php#L418

I could be wrong, but I just recently enabled 2FA on my Microsoft Account, and that may have had something to do with what's going on. The error is:

```
[04-Feb-2020 16:32:44 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://login.microsoftonline.com/common/oauth2/v2.0/token` resulted in a `400 Bad Request` response:
{"error":"invalid_grant","error_description":"AADSTS70000: The provided value for the 'code' parameter is not valid.\r\n (truncated...)
 in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 ... in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

What I feel like could be happening is:
1. Authorize Application
2. Store Access/Refresh Token
3. **Modify/Enable 2FA settings on Authenticated account**
4. Attempt to use application
5. Get Fatal Error during `$client->renewAccessToken()`.

I'm still not 100% sure enabling 2FA has cause the problem, but wanted to get your feedback to see what could be the issue and/or if you could reproduce it.

**Comment by krizalys** [comment]
@solepixel I have never tested my library with multi-factor, changes may be needed before I can propose official support of this scenario. I'll have to look into it.

According to https://help.k2.com/kb002269, enabling 2FA invalidates all OAuth tokens. A work around for your use case is to catch the exception and force the user to re-login. When they do, you save the new tokens over the invalidated ones.
