### ISSUE TITLE
Does this library currently support OneDrive for Business and Onedrive for Sharepoint?

### ISSUE THREAD

**Issue by tudders** [krizalys/onedrive-php-sdk#79]
Hi Kriz.

I can see some interesting stuff in the proxy folders suggesting the library may have business and sharepoint functionality - which as far as I can tell, is a change to the endpoint at minimum.

Does this functionality exist?

**Comment by krizalys** [comment]
@tudders This functionality is not officially supported, because I do not have access to a business/sharepoint account to test it. If you do, your contributions are welcome :)

**Comment by Dibbyo456** [comment]
@krizalys I can provide you a business account if you want it.
