### ISSUE TITLE
authentication not working after following all the instruction. Please help

### ISSUE THREAD

**Issue by apurbajnu** [krizalys/onedrive-php-sdk#80]
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://login.microsoftonline.com/common/oauth2/v2.0/token` resulted in a `400 Bad Request` response: {"error":"invalid_request","error_description":"AADSTS50194: Application '24a468f9-d56f-4259-984f-36bd0012f799'(test-app (truncated...) in /Users/apurbapodder/public_folder/chunk-upload/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /Users/apurbapodder/public_folder/chunk-upload/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /Users/apurbapodder/public_folder/chunk-upload/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /Users/apurbapodder/public_folder/chunk-upload/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /Users/apurbapod in /Users/apurbapodder/public_folder/chunk-upload/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

**Comment by krizalys** [comment]
@apurbajnu Perhaps your application is not registered properly?

In particular, make sure that you have added a "registration" with a "Web Redirect URI" which is valid and can be accessed from outside your network. Please reopen with more details if this does not solve it. Thanks.
