### ISSUE TITLE
how does another user pull the file list ?

### ISSUE THREAD

**Issue by ahmethmo** [krizalys/onedrive-php-sdk#82]
Sorry for my bad english. I used api and started it. example:

```
$deger = $client->getDriveItemById('680B****!2777');
echo 'parent Id : '.$deger->parentReference->id .'</br>';
echo 'id : '.$deger->id .'</br>';
echo 'name : '.$deger->name .'</br>';
echo 'web Url : '.$deger->webUrl.'</br>';
```

This code work well, output:

> parent Id : 680BF**!2773
> id : 680BFF**!2777
> name : musteri kabul.xlsx
> web Url : https://1drv.ms/x/s!A***wtolVk

But if i user another user. an error occurs. this is the error:

> Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://graph.microsoft.com/v1.0/me/drive/items/680BFF***!2777` resulted in a `404 Not Found` response: { "error": { "code": "itemNotFound", "message": "Item does not exist", "innerError": { "request (truncated...) in C:\wamp64\www\exe\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\wamp64\www\exe\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\wamp64\www\exe\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\wamp64\www\exe\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 C:\wamp64\www\exe\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure} in C:\wamp64\www\exe\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

I think it's a problem of access. If the user goes to the link "Url : https://1drv.ms/x/s!A***wtolVk" . He can open that link. What can i do ??

thanks in advance

**Comment by krizalys** [comment]
@ahmethmo Do the two users have access to the same drive (with the same drive ID)?

Please reopen when you have an answer.
