### ISSUE TITLE
Expire time and access_token question

### ISSUE THREAD

**Issue by itstheusername** [krizalys/onedrive-php-sdk#83]
Hello,

I wanted to build a app for my project that lists my drive files, i was trying a nodejs api "sdk" but that requires to login on app every 60 minutes, and i see yours is a bit different so i have 2 questions 

after setup i'm seeing this type of code
```
https://example.com/?code=M4bedee2a-xxx-xxx-xxx-b4f992a0cb61
```
this doesn't look like a token so i got your page https://github.com/krizalys/onedrive-php-sdk#step-3-get-an-oauth-access-token
and named it index.php, and i tried to execute this whole project is workin then i did
```php
print_r($_SESSION);
```
and i got access token, however same as nodejs expire code is 60min, this doesn't help me much,

So is there some way that doesn't require me to be online every 60 minutes to generate a new token? any idea?

thanks

**Comment by krizalys** [comment]
Thanks for your question @itstheusername.

Correct, 3600 seconds is the built-in token lifetime.

If you need more time than that, your application can renew the token before it expires (for example, every 3500 seconds) **without user interaction**, using `Client::renewAccessToken()`: https://github.com/krizalys/onedrive-php-sdk/blob/2.6.0/src/Client.php#L402

For your app to be able to renew tokens, it needs to pass `offline_access` to the scopes your app is requesting when you obtain the login URL, eg:

```php
$myLoginUrl = $client->getLogInUrl([
    'files.read',
    'files.read.all',
    'files.readwrite',
    'files.readwrite.all',
    // ...
    'offline_access', // <-- your app needs this
], 'http://my-redirect-uri.com');
```

Here is an example usage from the test suite: https://github.com/krizalys/onedrive-php-sdk/blob/2.6.0/test/functional/KrizalysOnedriveTest.php#L52

Please note that refresh tokens also expire after much longer period (1 year I think). Past this duration, the whole process can be repeated, eg. user interaction and subsequent token renewals.
