### ISSUE TITLE
How to get file from folder

### ISSUE THREAD

**Issue by iantearle** [krizalys/onedrive-php-sdk#86]
Can't find a usable example of this, but could you explain how I would get a file from a specific folder?

I want to retrieve a download url for an mp3 from a specified folder on one drive.

**Comment by krizalys** [comment]
@iantearle You have a few options:

If you already have a reference to a folder ($sandbox in this example): get the list of all items it contains:
https://github.com/krizalys/onedrive-php-sdk/blob/master/test/functional/Proxy/DriveItemProxyTest.php#L154-L162

If you do not have a reference to a folder, but do have an absolute path to the file: get an by path:
https://github.com/krizalys/onedrive-php-sdk/blob/master/test/functional/ClientTest.php#L226
