### ISSUE TITLE
add Support for PHP8

### ISSUE THREAD

**Issue by boredom2** [krizalys/onedrive-php-sdk#88]
Hi there,

please extend your Package Information to support PHP8 - its currently not installable under this Environment.
But as far as we see, the Library is working fine there.

Thanks!

**Comment by krizalys** [comment]
Alright @boredom2, let's do it!
We're dependent on https://github.com/microsoftgraph/msgraph-sdk-php/issues/359 to be resolved first, +1 there to bring PHP 8 to our SDK.

**Comment by boredom2** [comment]
Thats great, thanks!

**Comment by krizalys** [comment]
@boredom2 I just released version 3.0.0, which supports PHP 8, check it out!

**Comment by boredom2** [comment]
Thats great, thanks a lot!
