### ISSUE TITLE
How to upload a new file in existing folder

### ISSUE THREAD

**Issue by aravintha** [krizalys/onedrive-php-sdk#9]
How to upload a new file in existing folder

**Comment by krizalys** [comment]
1. Get an `Object` instance to the existing folder using `Client::fetchObject()`
2. Use `Folder::createFile()` on the returned object and pass it your file's contents/handle

**Comment by huydang284** [comment]
We have to save folder id? How about folder that we dont know it's id?

**Comment by aravintha** [comment]
There is one way. You can find the folder id by reading all the folders in OneDrive.

**Comment by huydang284** [comment]
@aravintha thank you. I found the solution :+1:
