### ISSUE TITLE
composer guzzlehttp/guzzle version

### ISSUE THREAD

**Issue by pietos** [krizalys/onedrive-php-sdk#92]
One of the composer requirements it to use version 6.3.3, in my project I use 7.3.0.
Is 6.3.3 really a dependency or can the line be changed from:

"guzzlehttp/guzzle": "^6.3.3",

to 

"guzzlehttp/guzzle": ">=6.3.3",

Error:
Using version ^3.0 for krizalys/onedrive-php-sdk
./composer.json has been updated
Running composer update krizalys/onedrive-php-sdk
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires krizalys/onedrive-php-sdk ^3.0 -> satisfiable by krizalys/onedrive-php-sdk[3.0.0].
    - krizalys/onedrive-php-sdk 3.0.0 requires guzzlehttp/guzzle ^6.3.3 -> found guzzlehttp/guzzle[6.3.3, ..., 6.5.5] but the package is fixed to 7.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by krizalys** [comment]
@pietos I released 3.1.0 which is loosening the requirements on Guzzle and supports both 6 and 7. Check it out.
