### ISSUE TITLE
About show file/image preview on my site

### ISSUE THREAD

**Issue by hetaldobariya117** [krizalys/onedrive-php-sdk#95]
Hello 

Greetings for the day

I have upload file one drive using this API. I have successfully uploaded file with OneDrive but right now I am facing problem on show preview on onedrive uploaded on my site.

I haven't able to show that uploaded file on my site. I have show WebUrl link on Iframe.

I have also some other issue.
1) I haven't able to get WebUrl and Download Url using API. (See screenshot: https://www.screencast.com/t/ROv3XHaOl)
2) I want to create my sub folder in one main folder. 
	e.g, I want to upload cloths, manware, womenware on one my main folder "online_shopping" folder. this online_shopping folder I have already created manually on one drive. I have generate sub folder(cloths, manware, womenware) using "CreateFolder" API. Those folders(cloths, manware, womenware) are created successfully.
3) Now I want to show images and file on my site and images and file already uploaded on above folder.

Kindly would you please help me to short out those problem. because I have spend lots of time to solve it but still not able to find effective solution.

Thanks

**Comment by krizalys** [comment]
Hi @hetaldobariya117 not sure to have understood your problem correctly. Let me try to answer.

1. Your screenshot shows that you got both `webUrl` and `downloadUrl`, what's the problem?

2. If you would like to create a folder A in another folder B, your first need to obtain a reference to folder B. If folder B is not the root of the OneDrive account, you need to first "navigate" to it by using `DriveItemProxy::getChildren` from its parent and locate the child:

```php
$children = $client->getRoot()->getChildren();

foreach ($children as $child) {
    if ($child->name == 'B') {
      $child->createFolder('A'); // or repeat this logic for a deeper file hierarchy: $child->getChildren()
      break;
    }
}
```

3. If you put your images in the "Public" folder, they should be accessible to the world via their "webUrl" (eg. you can embed them in HTML: `<img src="webUrl">`), however, as I understand, the purpose of this "webUrl" is to share a document to someone (eg. email a link to a photo) - embedding images on a website may not be allowed by OneDrive ToS - I'd recommend that you look at their legal conditions to avoid having your account restricted - perhaps you would be better off storing your images on a CDN/hosting provider

Hopefully, I have answered your questions - please reopen if not.

**Comment by hetaldobariya117** [comment]
Thanks you so much for solution. point 2 is work for me. I have already get solution for point Point 1 and point 2.
